[pytest]
# tell pytest where your tests live
testpaths = tests

# prepend the project root to PYTHONPATH so your package is importable
pythonpath = .

markers =
    integration: slow integration tests against live site