Import('*')

env.Python(
    target = ['#output/derived/prescrape/post1790_cd/geo_standardized_CD_post1790.csv'],
    source = ['#source/derived/prescrape/post1790_cd/standardize_geography.py']
)

env.Python(
    target = ['#output/derived/prescrape/post1790_cd/geo_name_standardized_CD_post1790.csv',
              '#output/derived/prescrape/post1790_cd/check/name_changes_list.csv'],
    source = ['#source/derived/prescrape/post1790_cd/clean_names_and_deduplicate.py',
              '#output/derived/prescrape/post1790_cd/geo_standardized_CD_post1790.csv']
)
